// Human-readable labels for every known turn log category.
// Unknown codes fall back to the raw code string at point of use.
export const LOG_CATEGORY_LABELS: Readonly<Record<string, string>> = {
  basic_turn_advancement: "Turn advancement",
  "building.auto_deconstructed": "Building auto-deconstructed",
  "building.recovered": "Building recovered",
  "building.suspended": "Building suspended",
  "citizen.born": "Citizen born",
  "citizen.consumed_food_water": "Food & water consumed",
  "citizen.died_homeless": "Died homeless",
  "citizen.starved": "Starvation",
  "construction.completed": "Construction completed",
  "construction.paused": "Construction paused",
  "construction.progress": "Construction progress",
  "deposit.depleted": "Deposit depleted",
  "deposit.processed": "Deposit processed",
  "event.building_destroyed": "Event: building destroyed",
  "event.consumption_multiplier": "Event: consumption multiplier",
  "event.deposit_discovered": "Event: deposit discovered",
  "event.deposit_destroyed": "Event: deposit destroyed",
  "event.managed_population_change": "Event: population change",
  "event.population_boost": "Event: population boost",
  "event.population_loss": "Event: population loss",
  "event.production_multiplier": "Event: production multiplier",
  "event.resource_drain": "Event: resource drain",
  "event.resource_grant": "Event: resource grant",
  "event.upkeep_multiplier": "Event: upkeep multiplier",
  homeless: "Homeless",
  "managed_population.declining": "Managed population declining",
  "managed_population.extinct": "Managed population extinct",
  manual_deconstruct_overshoot: "Manual deconstruct overshoot",
  "partnership.formed": "Partnership formed",
  "partnership.widowed": "Partnership widowed",
  "passive_effect.applied": "Passive effect applied",
  "settlement.homelessness_occurred": "Homelessness event",
  "settlement.starvation_occurred": "Starvation event",
  "standard_job.processed": "Job processed",
  starvation: "Starvation",
  "stockpile.clamped": "Stockpile clamped",
  "stockpile.decayed": "Stockpile decay",
  tampered: "Tampered",
  "trade_route.paused": "Trade route paused",
  "trade_route.resumed": "Trade route resumed",
};
