// Human-readable labels for every known turn log category.
// Unknown codes fall back to the raw code string at point of use.
export const LOG_CATEGORY_LABELS: Readonly<Record<string, string>> = {
  basic_turn_advancement: "Turn Advancement",
  "building.auto_deconstructed": "Building Auto-Deconstructed",
  "building.recovered": "Building Recovered",
  "building.suspended": "Building Suspended",
  "citizen.born": "Citizen Born",
  "citizen.consumed_food_water": "Food & Water Consumed",
  "citizen.died_homeless": "Died Homeless",
  "citizen.starved": "Starvation",
  "construction.completed": "Construction Completed",
  "construction.paused": "Construction Paused",
  "construction.progress": "Construction Progress",
  "deposit.depleted": "Deposit Depleted",
  "deposit.processed": "Deposit Processed",
  "event.building_destroyed": "Event: Building Destroyed",
  "event.consumption_multiplier": "Event: Consumption Multiplier",
  "event.deposit_discovered": "Event: Deposit Discovered",
  "event.deposit_destroyed": "Event: Deposit Destroyed",
  "event.managed_population_change": "Event: Population Change",
  "event.population_boost": "Event: Population Boost",
  "event.population_loss": "Event: Population Loss",
  "event.production_multiplier": "Event: Production Multiplier",
  "event.resource_drain": "Event: Resource Drain",
  "event.resource_grant": "Event: Resource Grant",
  "event.upkeep_multiplier": "Event: Upkeep Multiplier",
  homeless: "Homeless",
  "managed_population.declining": "Managed Population Declining",
  "managed_population.extinct": "Managed Population Extinct",
  manual_deconstruct_overshoot: "Manual Deconstruct Overshoot",
  "partnership.formed": "Partnership Formed",
  "partnership.widowed": "Partnership Widowed",
  "passive_effect.applied": "Passive Effect Applied",
  "settlement.homelessness_occurred": "Homelessness Event",
  "settlement.starvation_occurred": "Starvation Event",
  "standard_job.processed": "Job Processed",
  starvation: "Starvation",
  "stockpile.clamped": "Stockpile Clamped",
  "stockpile.decayed": "Stockpile Decay",
  tampered: "Tampered",
  "trade_route.paused": "Trade Route Paused",
  "trade_route.resumed": "Trade Route Resumed",
};
