import {
  Amphora,
  Anchor,
  Antenna,
  Anvil,
  Apple,
  Atom,
  Award,
  Axe,
  Baby,
  Banana,
  Bandage,
  Banknote,
  Barrel,
  Battery,
  Beaker,
  Bean,
  Beef,
  Beer,
  Bike,
  Bird,
  Bone,
  Book,
  BookOpen,
  Box,
  Boxes,
  Bug,
  Building,
  Building2,
  Calendar,
  Candy,
  Car,
  Carrot,
  Castle,
  Cat,
  Cherry,
  CircleHelp,
  Church,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Coffee,
  Cog,
  Coins,
  Compass,
  Container,
  Cookie,
  Cpu,
  Croissant,
  Crown,
  CupSoda,
  Diamond,
  Dna,
  Dog,
  Donut,
  Drill,
  Droplet,
  Droplets,
  Drumstick,
  Egg,
  EggFried,
  Factory,
  Feather,
  Fish,
  FishSymbol,
  Flag,
  FlagTriangleRight,
  Flame,
  FlaskConical,
  Flower,
  Flower2,
  Footprints,
  Fuel,
  Gauge,
  Gem,
  Gift,
  GlassWater,
  Globe,
  Grape,
  Grid3x3,
  Hammer,
  Hand,
  HandMetal,
  Heart,
  Home,
  Hospital,
  IceCreamCone,
  Key,
  Landmark,
  Layers,
  Leaf,
  LeafyGreen,
  Library,
  Lightbulb,
  Lock,
  Map,
  MapPin,
  Medal,
  Microscope,
  Milk,
  Moon,
  Mountain,
  MountainSnow,
  Nut,
  Package,
  PackageOpen,
  Paintbrush,
  Palette,
  PawPrint,
  Pickaxe,
  Pill,
  Pizza,
  Plane,
  Popcorn,
  Puzzle,
  Rabbit,
  Radio,
  Rat,
  Recycle,
  Rocket,
  Ruler,
  Salad,
  Sandwich,
  Satellite,
  School,
  Scissors,
  Scroll,
  ScrollText,
  Settings,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  Skull,
  Snail,
  Snowflake,
  Soup,
  Sparkles,
  Sprout,
  Squirrel,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Tent,
  TestTube,
  ThumbsUp,
  Timer,
  Tractor,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  Trophy,
  Truck,
  Turtle,
  Unlock,
  User,
  UserCheck,
  Users,
  Wallet,
  Warehouse,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

import {
  bareGameIconName,
  createGameIconComponent,
  isGameIconName,
} from "@/components/shared/iconPicker/GameIcons";

/**
 * Curated set of game-relevant Lucide icons, keyed by a stable kebab-case
 * name (the value stored in each config entity's `icon` column). Lucide has
 * thousands of icons; this list is a hand-picked subset so the picker grid
 * stays browsable and every stored value maps to a name we control (renaming
 * a key here would silently orphan existing data, so treat keys as stable
 * identifiers, not display labels).
 */
export const CURATED_ICONS: Record<string, LucideIcon> = {
  // Food
  wheat: Wheat,
  apple: Apple,
  banana: Banana,
  bean: Bean,
  beef: Beef,
  carrot: Carrot,
  cherry: Cherry,
  coffee: Coffee,
  cookie: Cookie,
  croissant: Croissant,
  "cup-soda": CupSoda,
  donut: Donut,
  drumstick: Drumstick,
  egg: Egg,
  "egg-fried": EggFried,
  fish: Fish,
  "fish-symbol": FishSymbol,
  grape: Grape,
  milk: Milk,
  sandwich: Sandwich,
  salad: Salad,
  soup: Soup,
  "ice-cream-cone": IceCreamCone,
  popcorn: Popcorn,
  pizza: Pizza,
  candy: Candy,
  // Tools
  pickaxe: Pickaxe,
  hammer: Hammer,
  axe: Axe,
  wrench: Wrench,
  shovel: Shovel,
  scissors: Scissors,
  anvil: Anvil,
  drill: Drill,
  ruler: Ruler,
  paintbrush: Paintbrush,
  hand: Hand,
  "hand-metal": HandMetal,
  // Nature & elements
  flame: Flame,
  zap: Zap,
  sparkles: Sparkles,
  droplet: Droplet,
  droplets: Droplets,
  waves: Waves,
  wind: Wind,
  snowflake: Snowflake,
  sun: Sun,
  moon: Moon,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  "cloud-lightning": CloudLightning,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  "tree-pine": TreePine,
  "tree-deciduous": TreeDeciduous,
  trees: Trees,
  sprout: Sprout,
  leaf: Leaf,
  "leafy-green": LeafyGreen,
  flower: Flower,
  "flower-2": Flower2,
  cloud: Cloud,
  sunrise: Sunrise,
  sunset: Sunset,
  // Animals
  bug: Bug,
  cat: Cat,
  dog: Dog,
  rabbit: Rabbit,
  bird: Bird,
  "paw-print": PawPrint,
  feather: Feather,
  turtle: Turtle,
  rat: Rat,
  squirrel: Squirrel,
  snail: Snail,
  // Buildings
  home: Home,
  warehouse: Warehouse,
  building: Building,
  "building-2": Building2,
  castle: Castle,
  church: Church,
  landmark: Landmark,
  tent: Tent,
  factory: Factory,
  store: Store,
  school: School,
  hospital: Hospital,
  library: Library,
  // Resources & trade
  gem: Gem,
  diamond: Diamond,
  coins: Coins,
  banknote: Banknote,
  wallet: Wallet,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  package: Package,
  "package-open": PackageOpen,
  boxes: Boxes,
  box: Box,
  container: Container,
  truck: Truck,
  ship: Ship,
  anchor: Anchor,
  compass: Compass,
  map: Map,
  "map-pin": MapPin,
  flag: Flag,
  "flag-triangle-right": FlagTriangleRight,
  barrel: Barrel,
  amphora: Amphora,
  "glass-water": GlassWater,
  beer: Beer,
  wine: Wine,
  nut: Nut,
  tractor: Tractor,
  // People & misc
  users: Users,
  user: User,
  "user-check": UserCheck,
  baby: Baby,
  crown: Crown,
  skull: Skull,
  bone: Bone,
  footprints: Footprints,
  // Knowledge & utility
  book: Book,
  "book-open": BookOpen,
  "scroll-text": ScrollText,
  scroll: Scroll,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  lightbulb: Lightbulb,
  battery: Battery,
  fuel: Fuel,
  gauge: Gauge,
  cog: Cog,
  settings: Settings,
  cpu: Cpu,
  wifi: Wifi,
  radio: Radio,
  antenna: Antenna,
  // Vehicles & misc
  plane: Plane,
  car: Car,
  bike: Bike,
  rocket: Rocket,
  satellite: Satellite,
  globe: Globe,
  // Cleanup & misc
  recycle: Recycle,
  "trash-2": Trash2,
  // Time & award
  timer: Timer,
  clock: Clock,
  calendar: Calendar,
  star: Star,
  heart: Heart,
  "thumbs-up": ThumbsUp,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  gift: Gift,
  // Materials & science
  layers: Layers,
  "grid-3x3": Grid3x3,
  puzzle: Puzzle,
  palette: Palette,
  beaker: Beaker,
  "flask-conical": FlaskConical,
  "test-tube": TestTube,
  microscope: Microscope,
  atom: Atom,
  dna: Dna,
  syringe: Syringe,
  pill: Pill,
  stethoscope: Stethoscope,
  bandage: Bandage,
};

/** Ordered list of curated icon names, for grid rendering / search. */
export const CURATED_ICON_NAMES: readonly string[] = Object.keys(
  CURATED_ICONS,
).sort((a, b) => a.localeCompare(b));

/** Fallback icon for unknown or null icon names. */
export const FALLBACK_ICON: LucideIcon = CircleHelp;

/**
 * Resolves an entity's stored `icon` name to a Lucide icon component,
 * falling back to a neutral placeholder for null/unknown values so a bad or
 * stale name (e.g. after a curated set change) never crashes rendering.
 */
export function resolveEntityIcon(name: string | null | undefined): LucideIcon {
  if (name === null || name === undefined || name.length === 0) {
    return FALLBACK_ICON;
  }
  if (isGameIconName(name)) {
    return createGameIconComponent(bareGameIconName(name));
  }
  return CURATED_ICONS[name] ?? FALLBACK_ICON;
}

/** Human-readable label for a curated icon name, e.g. "cup-soda" -> "Cup Soda". */
export function formatIconLabel(name: string): string {
  const bareName = isGameIconName(name) ? bareGameIconName(name) : name;
  return bareName
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
