// Populated multi-settlement world fixture for the golden determinism
// regression test (`end-turn-simulation/goldenDeterminism.test.ts`).
//
// This snapshot is deliberately broad: three settlements across two nations,
// sixteen citizens (partnered, single, child, enlisted), standard/deposit/
// trader/husbandry/culling jobs, buildings with storage + population-cap +
// education effects, a construction project, a trade route, tax + tribute +
// currency state, an army, and a sustained event. The goal is to exercise as
// many phases as possible in one run so that any behaviour change in the
// engine shows up as a golden diff.
//
// The seeded RNG streams are keyed on `worldId` + `turnNumber`, so both are
// pinned here. Do not change them casually — doing so re-rolls every random
// outcome in the golden.
//
// Cross-runtime module: no browser APIs, no @/ alias, explicit .ts extensions.

import type { SimulationInputState } from "./simulationTypes.ts";

export const GOLDEN_WORLD_ID = "w-golden";
export const GOLDEN_TURN_NUMBER = 42;
export const GOLDEN_TRANSITION_ID = "tt-golden";

const RESOURCE_IDS = {
  food: "r-food",
  iron: "r-iron",
  stone: "r-stone",
  water: "r-water",
  wood: "r-wood",
  wool: "r-wool",
} as const;

/**
 * Builds the golden world input state.
 *
 * Returns a fresh object on every call so a caller can never mutate the
 * fixture out from under another test.
 */
export function makeGoldenWorldInput(): SimulationInputState {
  return {
    armies: [
      {
        fundingSource: "nation",
        id: "a-north",
        name: "Northern Host",
        nationId: "n-north",
        stationedSettlementId: "s-beta",
      },
    ],
    armyUnits: [{ armyId: "a-north", id: "au-spears", unitTypeId: "ut-spear" }],
    buildingBlueprints: [
      { gracePeriodTurns: 2, id: "bp-granary", maxInstancesPerSettlement: 2, name: "Granary" },
      { gracePeriodTurns: 1, id: "bp-house", maxInstancesPerSettlement: null, name: "Longhouse" },
      { gracePeriodTurns: 3, id: "bp-school", maxInstancesPerSettlement: 1, name: "School" },
    ],
    buildingTiers: [
      {
        buildingBlueprintId: "bp-granary",
        constructionCostsJson: [{ amount: 20, resourceId: RESOURCE_IDS.wood }],
        effectsJson: [
          { amount: 120, resourceId: RESOURCE_IDS.food, type: "resource_storage_increase" },
          { amount: 5, type: "population_cap_increase" },
        ],
        id: "bt-granary-1",
        tierNumber: 1,
        upkeepCostsJson: [{ amount: 2, resourceId: RESOURCE_IDS.wood }],
        workerTurnsRequired: 6,
      },
      {
        buildingBlueprintId: "bp-house",
        constructionCostsJson: [{ amount: 10, resourceId: RESOURCE_IDS.wood }],
        effectsJson: [
          { amount: 8, type: "population_cap_increase" },
          { amount: 1, jobId: "j-farm", type: "job_capacity_increase" },
        ],
        id: "bt-house-1",
        tierNumber: 1,
        upkeepCostsJson: [{ amount: 1, resourceId: RESOURCE_IDS.wood }],
        workerTurnsRequired: 4,
      },
      {
        buildingBlueprintId: "bp-school",
        constructionCostsJson: [{ amount: 30, resourceId: RESOURCE_IDS.stone }],
        effectsJson: [
          { amount: 2, resourceId: RESOURCE_IDS.wool, type: "passive_resource_production" },
          {
            levels: [
              { fromLevelId: null, toLevelId: "el-basic", turns: 2 },
              { fromLevelId: "el-basic", toLevelId: "el-advanced", turns: 4 },
            ],
            studentsPerTeacher: 4,
            teacherCapacity: 1,
            teacherJobId: "j-teacher",
            type: "education",
          },
        ],
        id: "bt-school-1",
        tierNumber: 1,
        upkeepCostsJson: [{ amount: 1, resourceId: RESOURCE_IDS.food }],
        workerTurnsRequired: 8,
      },
    ],
    calendarConfig: {
      dateFormatTemplate: "{day} {month} {year}",
      months: [
        { dayCount: 30, index: 0, name: "Frostmoon" },
        { dayCount: 30, index: 1, name: "Seedmoon" },
      ],
      startingDayOfMonth: 1,
      startingMonthIndex: 0,
      startingWeekdayOffset: 0,
      startingYear: 700,
      weekdays: [
        { index: 0, name: "Firstday" },
        { index: 1, name: "Secondday" },
      ],
    },
    citizenAssignments: [
      {
        assignedOnTurnNumber: 30,
        assignmentType: "standard_job",
        citizenId: "c-002",
        constructionProjectId: null,
        depositInstanceId: null,
        jobId: "j-farm",
        managedPopulationInstanceId: null,
        tradeRouteEnd: null,
        tradeRouteId: null,
      },
      {
        assignedOnTurnNumber: 31,
        assignmentType: "standard_job",
        citizenId: "c-003",
        constructionProjectId: null,
        depositInstanceId: null,
        jobId: "j-farm",
        managedPopulationInstanceId: null,
        tradeRouteEnd: null,
        tradeRouteId: null,
      },
      {
        assignedOnTurnNumber: 32,
        assignmentType: "husbandry",
        citizenId: "c-004",
        constructionProjectId: null,
        depositInstanceId: null,
        jobId: "j-shepherd",
        managedPopulationInstanceId: "mp-sheep",
        tradeRouteEnd: null,
        tradeRouteId: null,
      },
      {
        assignedOnTurnNumber: 33,
        assignmentType: "trade_route",
        citizenId: "c-016",
        constructionProjectId: null,
        depositInstanceId: null,
        jobId: "j-trader",
        managedPopulationInstanceId: null,
        tradeRouteEnd: "origin",
        tradeRouteId: "tr-alpha-beta",
      },
      {
        assignedOnTurnNumber: 33,
        assignmentType: "trade_route",
        citizenId: "c-008",
        constructionProjectId: null,
        depositInstanceId: null,
        jobId: "j-trader",
        managedPopulationInstanceId: null,
        tradeRouteEnd: "destination",
        tradeRouteId: "tr-alpha-beta",
      },
      {
        assignedOnTurnNumber: 34,
        assignmentType: "deposit",
        citizenId: "c-006",
        constructionProjectId: null,
        depositInstanceId: "d-ironvein",
        jobId: "j-miner",
        managedPopulationInstanceId: null,
        tradeRouteEnd: null,
        tradeRouteId: null,
      },
      {
        assignedOnTurnNumber: 35,
        assignmentType: "standard_job",
        citizenId: "c-007",
        constructionProjectId: null,
        depositInstanceId: null,
        jobId: "j-woodcutter",
        managedPopulationInstanceId: null,
        tradeRouteEnd: null,
        tradeRouteId: null,
      },
      {
        assignedOnTurnNumber: 36,
        assignmentType: "culling",
        citizenId: "c-009",
        constructionProjectId: null,
        depositInstanceId: null,
        jobId: "j-butcher",
        managedPopulationInstanceId: "mp-sheep",
        tradeRouteEnd: null,
        tradeRouteId: null,
      },
      {
        assignedOnTurnNumber: 37,
        assignmentType: "construction_project",
        citizenId: "c-012",
        constructionProjectId: "cp-gamma-granary",
        depositInstanceId: null,
        jobId: null,
        managedPopulationInstanceId: null,
        tradeRouteEnd: null,
        tradeRouteId: null,
      },
      {
        assignedOnTurnNumber: 38,
        assignmentType: "standard_job",
        citizenId: "c-014",
        constructionProjectId: null,
        depositInstanceId: null,
        jobId: "j-farm",
        managedPopulationInstanceId: null,
        tradeRouteEnd: null,
        tradeRouteId: null,
      },
      {
        assignedOnTurnNumber: 38,
        assignmentType: "standard_job",
        citizenId: "c-015",
        constructionProjectId: null,
        depositInstanceId: null,
        jobId: "j-teacher",
        managedPopulationInstanceId: null,
        tradeRouteEnd: null,
        tradeRouteId: null,
      },
    ],
    citizens: [
      makeCitizen("c-001", "s-alpha", "male", 5, { roleNationId: "n-north" }),
      makeCitizen("c-002", "s-alpha", "female", 6),
      makeCitizen("c-003", "s-alpha", "male", 20),
      makeCitizen("c-004", "s-alpha", "female", 21),
      makeCitizen("c-005", "s-alpha", "male", 38, {
        parentACitizenId: "c-001",
        parentBCitizenId: "c-002",
      }),
      makeCitizen("c-016", "s-alpha", "female", 22),
      makeCitizen("c-017", "s-alpha", "male", 19),
      makeCitizen("c-006", "s-beta", "male", 8),
      makeCitizen("c-007", "s-beta", "female", 9),
      makeCitizen("c-008", "s-beta", "male", 24),
      makeCitizen("c-009", "s-beta", "female", 25),
      makeCitizen("c-010", "s-beta", "male", 12),
      makeCitizen("c-011", "s-beta", "male", 13),
      makeCitizen("c-018", "s-beta", "female", 18),
      makeCitizen("c-012", "s-gamma", "female", 10),
      makeCitizen("c-013", "s-gamma", "male", 11),
      makeCitizen("c-014", "s-gamma", "female", 26),
      makeCitizen("c-015", "s-gamma", "male", 27),
      makeCitizen("c-019", "s-gamma", "male", 17),
      makeCitizen("c-020", "s-gamma", "female", 16),
    ],
    constructionProjects: [
      {
        buildingBlueprintId: "bp-granary",
        id: "cp-gamma-granary",
        progressWorkerTurns: 5,
        queuePosition: 0,
        settlementId: "s-gamma",
        status: "in_progress",
        targetTierId: "bt-granary-1",
        upgradeSettlementBuildingId: null,
        workerTurnsRequired: 6,
      },
    ],
    depositTypeJobs: [
      {
        depositTypeId: "dt-iron",
        id: "dtj-iron",
        jobId: "j-miner",
        outputUnitsPerWorker: 3,
        workerInputsJson: [{ amountPerWorker: 1, resourceId: RESOURCE_IDS.food }],
      },
    ],
    depositTypes: [{ id: "dt-iron", name: "Iron Vein" }],
    deposits: [
      {
        depositTypeId: "dt-iron",
        id: "d-ironvein",
        maxWorkers: 3,
        name: "Beta Iron Vein",
        resources: [
          {
            depositInstanceId: "d-ironvein",
            id: "dr-ironvein-iron",
            remainingQuantity: 40,
            resourceId: RESOURCE_IDS.iron,
          },
        ],
        settlementId: "s-beta",
        status: "active",
      },
    ],
    educationEnrollments: [
      {
        citizenId: "c-013",
        enrolledTurnNumber: 40,
        id: "ee-gamma-basic",
        progressTurns: 1,
        settlementBuildingId: "sb-gamma-school",
        targetLevelId: "el-basic",
        worldId: GOLDEN_WORLD_ID,
      },
    ],
    educationLevels: [
      {
        id: "el-basic",
        name: "Basic",
        naturalBornPercent: 0,
        rank: 1,
        worldId: GOLDEN_WORLD_ID,
      },
      {
        id: "el-advanced",
        name: "Advanced",
        naturalBornPercent: 0,
        rank: 2,
        worldId: GOLDEN_WORLD_ID,
      },
    ],
    events: [
      {
        activateOnTransitionAfterTurnNumber: 40,
        durationType: "sustained",
        effectPayloadJsonb: {},
        effectType: "production_multiplier",
        effects: [
          {
            amountValue: null,
            depositInstanceId: null,
            effectType: "production_multiplier",
            id: "ef-bounty",
            isPercent: true,
            jobId: "j-farm",
            managedPopulationInstanceId: null,
            multiplierValue: 1.5,
            resourceId: null,
            settlementBuildingId: null,
          },
        ],
        id: "ev-bounty",
        remainingTransitions: 2,
        scopeSettlementId: "s-alpha",
        scopeType: "settlement",
        status: "active",
      },
    ],
    jobs: [
      {
        baseCapacity: 4,
        id: "j-farm",
        inputsJson: [{ amountPerWorker: 1, resourceId: RESOURCE_IDS.water }],
        jobType: "standard",
        linkedDepositTypeId: null,
        linkedManagedPopulationTypeId: null,
        name: "Farmer",
        outputsJson: [{ amountPerWorker: 4, resourceId: RESOURCE_IDS.food }],
        requiredEducationLevelId: null,
        traderCapacityPerWorker: null,
      },
      {
        baseCapacity: 3,
        id: "j-woodcutter",
        inputsJson: [],
        jobType: "standard",
        linkedDepositTypeId: null,
        linkedManagedPopulationTypeId: null,
        name: "Woodcutter",
        outputsJson: [{ amountPerWorker: 3, resourceId: RESOURCE_IDS.wood }],
        requiredEducationLevelId: null,
        traderCapacityPerWorker: null,
      },
      {
        baseCapacity: 2,
        id: "j-teacher",
        inputsJson: [],
        jobType: "standard",
        linkedDepositTypeId: null,
        linkedManagedPopulationTypeId: null,
        name: "Teacher",
        outputsJson: [],
        requiredEducationLevelId: null,
        traderCapacityPerWorker: null,
      },
      {
        baseCapacity: null,
        id: "j-miner",
        inputsJson: [],
        jobType: "deposit",
        linkedDepositTypeId: "dt-iron",
        linkedManagedPopulationTypeId: null,
        name: "Miner",
        outputsJson: [],
        requiredEducationLevelId: null,
        traderCapacityPerWorker: null,
      },
      {
        baseCapacity: null,
        id: "j-trader",
        inputsJson: [],
        jobType: "trader",
        linkedDepositTypeId: null,
        linkedManagedPopulationTypeId: null,
        name: "Trader",
        outputsJson: [],
        requiredEducationLevelId: null,
        traderCapacityPerWorker: 15,
      },
      {
        baseCapacity: null,
        id: "j-shepherd",
        inputsJson: [],
        jobType: "husbandry",
        linkedDepositTypeId: null,
        linkedManagedPopulationTypeId: "mpt-sheep",
        name: "Shepherd",
        outputsJson: [],
        requiredEducationLevelId: null,
        traderCapacityPerWorker: null,
      },
      {
        baseCapacity: null,
        id: "j-butcher",
        inputsJson: [],
        jobType: "culling",
        linkedDepositTypeId: null,
        linkedManagedPopulationTypeId: "mpt-sheep",
        name: "Butcher",
        outputsJson: [],
        requiredEducationLevelId: null,
        traderCapacityPerWorker: null,
      },
    ],
    managedPopulationCullingJobs: [
      {
        id: "mpcj-sheep",
        jobId: "j-butcher",
        managedPopulationTypeId: "mpt-sheep",
        maxCullPerWorker: 4,
      },
    ],
    managedPopulationHusbandryJobs: [
      {
        id: "mphj-sheep",
        jobId: "j-shepherd",
        managedPopulationTypeId: "mpt-sheep",
        workersPerNAnimals: 20,
      },
    ],
    managedPopulationTypes: [
      {
        cullingOutputsJson: [{ amountPerNAnimals: 6, resourceId: RESOURCE_IDS.food }],
        growthRate: 0.1,
        id: "mpt-sheep",
        maintenanceRulesJson: [{ amountPerNAnimals: 2, resourceId: RESOURCE_IDS.food }],
        name: "Sheep",
        regularOutputsJson: [{ amountPerNAnimals: 1, resourceId: RESOURCE_IDS.wool }],
      },
    ],
    managedPopulations: [
      {
        configuredCullQuantity: 3,
        currentCount: 24,
        id: "mp-sheep",
        managedPopulationTypeId: "mpt-sheep",
        name: "Alpha Flock",
        settlementId: "s-alpha",
        status: "active",
      },
    ],
    nationCurrencies: [
      {
        backingRatio: null,
        backingResourceId: null,
        confidence: 0.9,
        currencyType: "fiat",
        id: "cur-north",
        isInDefault: false,
        moneySupply: 1000,
        name: "Northern Mark",
        nationId: "n-north",
        reserveQuantity: 0,
      },
      {
        backingRatio: 2,
        backingResourceId: RESOURCE_IDS.iron,
        confidence: 1,
        currencyType: "resource_backed",
        id: "cur-south",
        isInDefault: false,
        moneySupply: 400,
        name: "Southern Bar",
        nationId: "n-south",
        reserveQuantity: 250,
      },
    ],
    nationCurrencyLedgerEntries: [
      { action: "mint", amount: 100, currencyId: "cur-north" },
      { action: "burn", amount: 20, currencyId: "cur-north" },
    ],
    nationOffices: [{ citizenId: "c-001", excludesFromLabor: true }],
    nationRelationships: [
      { currentStance: "neutral", fromNationId: "n-north", toNationId: "n-south" },
      { currentStance: "neutral", fromNationId: "n-south", toNationId: "n-north" },
    ],
    nationResourceStockpiles: [
      { nationId: "n-north", quantity: 60, resourceId: RESOURCE_IDS.food },
      { nationId: "n-north", quantity: 30, resourceId: RESOURCE_IDS.iron },
      { nationId: "n-south", quantity: 15, resourceId: RESOURCE_IDS.iron },
    ],
    nationTaxPolicies: [
      {
        exempt: false,
        flatAmount: 0,
        method: "percent_production",
        minStockpileFloor: 0,
        nationId: "n-north",
        rate: 0.1,
        settlementId: null,
        taxedResourceIds: null,
      },
      {
        exempt: false,
        flatAmount: 2,
        method: "flat",
        minStockpileFloor: 5,
        nationId: "n-south",
        rate: 0,
        settlementId: "s-gamma",
        taxedResourceIds: [RESOURCE_IDS.food],
      },
    ],
    nationTreaties: [
      {
        endsTurnNumber: 60,
        id: "t-tribute",
        marriageCitizenAId: null,
        marriageCitizenBId: null,
        proposerNationId: "n-north",
        responderNationId: "n-south",
        treatyType: "tribute",
        tributePayer: "proposer",
        tributeQuantityPerTurn: 5,
        tributeResourceId: RESOURCE_IDS.iron,
      },
      {
        endsTurnNumber: 42,
        id: "t-marriage",
        marriageCitizenAId: "c-005",
        marriageCitizenBId: "c-012",
        proposerNationId: "n-south",
        responderNationId: "n-north",
        treatyType: "royal_marriage",
        tributePayer: null,
        tributeQuantityPerTurn: null,
        tributeResourceId: null,
      },
    ],
    nations: [
      {
        governmentType: "monarchy",
        id: "n-north",
        name: "Northrealm",
        taxRate: 0.1,
        tradePolicy: "free",
      },
      {
        governmentType: "republic",
        id: "n-south",
        name: "Southrealm",
        taxRate: 0.05,
        tradePolicy: "free",
      },
    ],
    partnerships: [
      {
        citizenAId: "c-001",
        citizenBId: "c-002",
        endedOnTurnNumber: null,
        formedOnTurnNumber: 30,
        id: "pt-1",
        status: "active",
      },
      {
        citizenAId: "c-006",
        citizenBId: "c-007",
        endedOnTurnNumber: null,
        formedOnTurnNumber: 32,
        id: "pt-2",
        status: "active",
      },
    ],
    populationRules: {
      fertilityChance: 0.5,
      foodConsumptionPerCitizen: 1,
      homelessnessDecliningRate: 0.2,
      incestPreventionDepth: 2,
      maximumFertilityAgeTurns: 40,
      minimumPartnershipAgeTurns: 16,
      mourningPeriodTurns: 5,
      partnershipSeekChance: 0.8,
      starvationSeverityMultiplier: 0.5,
      waterConsumptionPerCitizen: 1,
    },
    resources: [
      { changeAmount: 0.05, changeMode: "percent", id: RESOURCE_IDS.food },
      { changeAmount: 0, changeMode: "flat", id: RESOURCE_IDS.water },
      { changeAmount: 0, changeMode: "flat", id: RESOURCE_IDS.wood },
      { changeAmount: 0, changeMode: "flat", id: RESOURCE_IDS.stone },
      { changeAmount: 0, changeMode: "flat", id: RESOURCE_IDS.iron },
      { changeAmount: 1, changeMode: "flat", id: RESOURCE_IDS.wool },
    ],
    settlementBuildings: [
      {
        activatedOnTurnNumber: 20,
        buildingBlueprintId: "bp-granary",
        currentTierId: "bt-granary-1",
        id: "sb-alpha-granary",
        missedUpkeepCount: 0,
        settlementId: "s-alpha",
        sourceProjectId: null,
        state: "active",
      },
      {
        activatedOnTurnNumber: 22,
        buildingBlueprintId: "bp-house",
        currentTierId: "bt-house-1",
        id: "sb-alpha-house",
        missedUpkeepCount: 1,
        settlementId: "s-alpha",
        sourceProjectId: null,
        state: "active",
      },
      {
        activatedOnTurnNumber: 25,
        buildingBlueprintId: "bp-house",
        currentTierId: "bt-house-1",
        id: "sb-beta-house",
        missedUpkeepCount: 0,
        settlementId: "s-beta",
        sourceProjectId: null,
        state: "active",
      },
      {
        activatedOnTurnNumber: 28,
        buildingBlueprintId: "bp-school",
        currentTierId: "bt-school-1",
        id: "sb-gamma-school",
        missedUpkeepCount: 0,
        settlementId: "s-gamma",
        sourceProjectId: null,
        state: "active",
      },
    ],
    settlements: [
      {
        autoReadyEnabled: false,
        id: "s-alpha",
        isReadyCurrentTurn: true,
        name: "Alpha",
        nationId: "n-north",
      },
      {
        autoReadyEnabled: true,
        id: "s-beta",
        isReadyCurrentTurn: false,
        name: "Beta",
        nationId: "n-north",
      },
      {
        autoReadyEnabled: false,
        id: "s-gamma",
        isReadyCurrentTurn: false,
        name: "Gamma",
        nationId: "n-south",
      },
    ],
    stockpiles: [
      { cap: 100, quantity: 40, resourceId: RESOURCE_IDS.food, settlementId: "s-alpha" },
      { cap: 100, quantity: 25, resourceId: RESOURCE_IDS.water, settlementId: "s-alpha" },
      { cap: 100, quantity: 30, resourceId: RESOURCE_IDS.wood, settlementId: "s-alpha" },
      { cap: 100, quantity: 10, resourceId: RESOURCE_IDS.wool, settlementId: "s-alpha" },
      { cap: 100, quantity: 12, resourceId: RESOURCE_IDS.food, settlementId: "s-beta" },
      { cap: 100, quantity: 8, resourceId: RESOURCE_IDS.water, settlementId: "s-beta" },
      { cap: 100, quantity: 18, resourceId: RESOURCE_IDS.wood, settlementId: "s-beta" },
      { cap: 100, quantity: 5, resourceId: RESOURCE_IDS.iron, settlementId: "s-beta" },
      { cap: 100, quantity: 6, resourceId: RESOURCE_IDS.food, settlementId: "s-gamma" },
      { cap: 100, quantity: 4, resourceId: RESOURCE_IDS.water, settlementId: "s-gamma" },
      { cap: 100, quantity: 14, resourceId: RESOURCE_IDS.wood, settlementId: "s-gamma" },
      { cap: 100, quantity: 9, resourceId: RESOURCE_IDS.stone, settlementId: "s-gamma" },
    ],
    systemResourceIds: { foodId: RESOURCE_IDS.food, freshWaterId: RESOURCE_IDS.water },
    tradeRoutes: [
      {
        destinationSettlementId: "s-beta",
        id: "tr-alpha-beta",
        legs: [
          { direction: "send", quantityPerTransition: 10, resourceId: RESOURCE_IDS.food },
          { direction: "receive", quantityPerTransition: 4, resourceId: RESOURCE_IDS.iron },
        ],
        originSettlementId: "s-alpha",
        status: "active",
      },
    ],
    turnNumber: GOLDEN_TURN_NUMBER,
    unitSoldiers: [
      { citizenId: "c-010", homeSettlementId: "s-beta", id: "us-1", unitId: "au-spears" },
      { citizenId: "c-011", homeSettlementId: "s-beta", id: "us-2", unitId: "au-spears" },
    ],
    unitTypes: [
      {
        desertionRate: 0.25,
        id: "ut-spear",
        upkeepCostsJson: [{ amount: 2, resourceId: RESOURCE_IDS.food }],
      },
    ],
    worldId: GOLDEN_WORLD_ID,
  };
}

function makeCitizen(
  id: string,
  settlementId: string,
  sex: "male" | "female",
  bornOnTurnNumber: number,
  overrides: {
    readonly parentACitizenId?: string;
    readonly parentBCitizenId?: string;
    readonly roleNationId?: string;
  } = {},
): SimulationInputState["citizens"][number] {
  return {
    bornOnTurnNumber,
    citizenType: "npc",
    cultureId: null,
    educationLevelId: null,
    givenName: id,
    id,
    namesetId: null,
    parentACitizenId: overrides.parentACitizenId ?? null,
    parentBCitizenId: overrides.parentBCitizenId ?? null,
    religionId: null,
    roleNationId: overrides.roleNationId ?? null,
    roleSettlementId: null,
    roleType: overrides.roleNationId === undefined ? "none" : "nation_manager",
    settlementId,
    sex,
    status: "alive",
    surname: null,
  };
}
