/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldsIndexRouteImport } from './routes/worlds.index'
import { Route as WorldsWorldIdRouteImport } from './routes/worlds.$worldId'
import { Route as WorldsWorldIdIndexRouteImport } from './routes/worlds.$worldId.index'
import { Route as WorldsWorldIdNationsRouteImport } from './routes/worlds.$worldId.nations'
import { Route as WorldsWorldIdConfigurationRouteImport } from './routes/worlds.$worldId.configuration'
import { Route as WorldsWorldIdNationsIndexRouteImport } from './routes/worlds.$worldId.nations.index'
import { Route as WorldsWorldIdNationsNationIdRouteImport } from './routes/worlds.$worldId.nations.$nationId'
import { Route as WorldsWorldIdCitizensCitizenIdRouteImport } from './routes/worlds.$worldId.citizens.$citizenId'
import { Route as WorldsWorldIdNationsNationIdIndexRouteImport } from './routes/worlds.$worldId.nations.$nationId.index'
import { Route as WorldsWorldIdNationsNationIdSettlementsSettlementIdRouteImport } from './routes/worlds.$worldId.nations.$nationId.settlements.$settlementId'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsIndexRoute = WorldsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorldsRoute,
} as any)
const WorldsWorldIdRoute = WorldsWorldIdRouteImport.update({
  id: '/$worldId',
  path: '/$worldId',
  getParentRoute: () => WorldsRoute,
} as any)
const WorldsWorldIdIndexRoute = WorldsWorldIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorldsWorldIdRoute,
} as any)
const WorldsWorldIdNationsRoute = WorldsWorldIdNationsRouteImport.update({
  id: '/nations',
  path: '/nations',
  getParentRoute: () => WorldsWorldIdRoute,
} as any)
const WorldsWorldIdConfigurationRoute =
  WorldsWorldIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => WorldsWorldIdRoute,
  } as any)
const WorldsWorldIdNationsIndexRoute =
  WorldsWorldIdNationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorldsWorldIdNationsRoute,
  } as any)
const WorldsWorldIdNationsNationIdRoute =
  WorldsWorldIdNationsNationIdRouteImport.update({
    id: '/$nationId',
    path: '/$nationId',
    getParentRoute: () => WorldsWorldIdNationsRoute,
  } as any)
const WorldsWorldIdCitizensCitizenIdRoute =
  WorldsWorldIdCitizensCitizenIdRouteImport.update({
    id: '/citizens/$citizenId',
    path: '/citizens/$citizenId',
    getParentRoute: () => WorldsWorldIdRoute,
  } as any)
const WorldsWorldIdNationsNationIdIndexRoute =
  WorldsWorldIdNationsNationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorldsWorldIdNationsNationIdRoute,
  } as any)
const WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute =
  WorldsWorldIdNationsNationIdSettlementsSettlementIdRouteImport.update({
    id: '/settlements/$settlementId',
    path: '/settlements/$settlementId',
    getParentRoute: () => WorldsWorldIdNationsNationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/worlds': typeof WorldsRouteWithChildren
  '/worlds/$worldId': typeof WorldsWorldIdRouteWithChildren
  '/worlds/': typeof WorldsIndexRoute
  '/worlds/$worldId/configuration': typeof WorldsWorldIdConfigurationRoute
  '/worlds/$worldId/nations': typeof WorldsWorldIdNationsRouteWithChildren
  '/worlds/$worldId/': typeof WorldsWorldIdIndexRoute
  '/worlds/$worldId/citizens/$citizenId': typeof WorldsWorldIdCitizensCitizenIdRoute
  '/worlds/$worldId/nations/$nationId': typeof WorldsWorldIdNationsNationIdRouteWithChildren
  '/worlds/$worldId/nations/': typeof WorldsWorldIdNationsIndexRoute
  '/worlds/$worldId/nations/$nationId/': typeof WorldsWorldIdNationsNationIdIndexRoute
  '/worlds/$worldId/nations/$nationId/settlements/$settlementId': typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/worlds': typeof WorldsIndexRoute
  '/worlds/$worldId/configuration': typeof WorldsWorldIdConfigurationRoute
  '/worlds/$worldId': typeof WorldsWorldIdIndexRoute
  '/worlds/$worldId/citizens/$citizenId': typeof WorldsWorldIdCitizensCitizenIdRoute
  '/worlds/$worldId/nations': typeof WorldsWorldIdNationsIndexRoute
  '/worlds/$worldId/nations/$nationId': typeof WorldsWorldIdNationsNationIdIndexRoute
  '/worlds/$worldId/nations/$nationId/settlements/$settlementId': typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/worlds': typeof WorldsRouteWithChildren
  '/worlds/$worldId': typeof WorldsWorldIdRouteWithChildren
  '/worlds/': typeof WorldsIndexRoute
  '/worlds/$worldId/configuration': typeof WorldsWorldIdConfigurationRoute
  '/worlds/$worldId/nations': typeof WorldsWorldIdNationsRouteWithChildren
  '/worlds/$worldId/': typeof WorldsWorldIdIndexRoute
  '/worlds/$worldId/citizens/$citizenId': typeof WorldsWorldIdCitizensCitizenIdRoute
  '/worlds/$worldId/nations/$nationId': typeof WorldsWorldIdNationsNationIdRouteWithChildren
  '/worlds/$worldId/nations/': typeof WorldsWorldIdNationsIndexRoute
  '/worlds/$worldId/nations/$nationId/': typeof WorldsWorldIdNationsNationIdIndexRoute
  '/worlds/$worldId/nations/$nationId/settlements/$settlementId': typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/worlds'
    | '/worlds/$worldId'
    | '/worlds/'
    | '/worlds/$worldId/configuration'
    | '/worlds/$worldId/nations'
    | '/worlds/$worldId/'
    | '/worlds/$worldId/citizens/$citizenId'
    | '/worlds/$worldId/nations/$nationId'
    | '/worlds/$worldId/nations/'
    | '/worlds/$worldId/nations/$nationId/'
    | '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/worlds'
    | '/worlds/$worldId/configuration'
    | '/worlds/$worldId'
    | '/worlds/$worldId/citizens/$citizenId'
    | '/worlds/$worldId/nations'
    | '/worlds/$worldId/nations/$nationId'
    | '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/worlds'
    | '/worlds/$worldId'
    | '/worlds/'
    | '/worlds/$worldId/configuration'
    | '/worlds/$worldId/nations'
    | '/worlds/$worldId/'
    | '/worlds/$worldId/citizens/$citizenId'
    | '/worlds/$worldId/nations/$nationId'
    | '/worlds/$worldId/nations/'
    | '/worlds/$worldId/nations/$nationId/'
    | '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  WorldsRoute: typeof WorldsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/': {
      id: '/worlds/'
      path: '/'
      fullPath: '/worlds/'
      preLoaderRoute: typeof WorldsIndexRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/worlds/$worldId': {
      id: '/worlds/$worldId'
      path: '/$worldId'
      fullPath: '/worlds/$worldId'
      preLoaderRoute: typeof WorldsWorldIdRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/worlds/$worldId/': {
      id: '/worlds/$worldId/'
      path: '/'
      fullPath: '/worlds/$worldId/'
      preLoaderRoute: typeof WorldsWorldIdIndexRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/$worldId/nations': {
      id: '/worlds/$worldId/nations'
      path: '/nations'
      fullPath: '/worlds/$worldId/nations'
      preLoaderRoute: typeof WorldsWorldIdNationsRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/$worldId/configuration': {
      id: '/worlds/$worldId/configuration'
      path: '/configuration'
      fullPath: '/worlds/$worldId/configuration'
      preLoaderRoute: typeof WorldsWorldIdConfigurationRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/$worldId/nations/': {
      id: '/worlds/$worldId/nations/'
      path: '/'
      fullPath: '/worlds/$worldId/nations/'
      preLoaderRoute: typeof WorldsWorldIdNationsIndexRouteImport
      parentRoute: typeof WorldsWorldIdNationsRoute
    }
    '/worlds/$worldId/nations/$nationId': {
      id: '/worlds/$worldId/nations/$nationId'
      path: '/$nationId'
      fullPath: '/worlds/$worldId/nations/$nationId'
      preLoaderRoute: typeof WorldsWorldIdNationsNationIdRouteImport
      parentRoute: typeof WorldsWorldIdNationsRoute
    }
    '/worlds/$worldId/citizens/$citizenId': {
      id: '/worlds/$worldId/citizens/$citizenId'
      path: '/citizens/$citizenId'
      fullPath: '/worlds/$worldId/citizens/$citizenId'
      preLoaderRoute: typeof WorldsWorldIdCitizensCitizenIdRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/$worldId/nations/$nationId/': {
      id: '/worlds/$worldId/nations/$nationId/'
      path: '/'
      fullPath: '/worlds/$worldId/nations/$nationId/'
      preLoaderRoute: typeof WorldsWorldIdNationsNationIdIndexRouteImport
      parentRoute: typeof WorldsWorldIdNationsNationIdRoute
    }
    '/worlds/$worldId/nations/$nationId/settlements/$settlementId': {
      id: '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
      path: '/settlements/$settlementId'
      fullPath: '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
      preLoaderRoute: typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRouteImport
      parentRoute: typeof WorldsWorldIdNationsNationIdRoute
    }
  }
}

interface WorldsWorldIdNationsNationIdRouteChildren {
  WorldsWorldIdNationsNationIdIndexRoute: typeof WorldsWorldIdNationsNationIdIndexRoute
  WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute: typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute
}

const WorldsWorldIdNationsNationIdRouteChildren: WorldsWorldIdNationsNationIdRouteChildren =
  {
    WorldsWorldIdNationsNationIdIndexRoute:
      WorldsWorldIdNationsNationIdIndexRoute,
    WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute:
      WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute,
  }

const WorldsWorldIdNationsNationIdRouteWithChildren =
  WorldsWorldIdNationsNationIdRoute._addFileChildren(
    WorldsWorldIdNationsNationIdRouteChildren,
  )

interface WorldsWorldIdNationsRouteChildren {
  WorldsWorldIdNationsNationIdRoute: typeof WorldsWorldIdNationsNationIdRouteWithChildren
  WorldsWorldIdNationsIndexRoute: typeof WorldsWorldIdNationsIndexRoute
}

const WorldsWorldIdNationsRouteChildren: WorldsWorldIdNationsRouteChildren = {
  WorldsWorldIdNationsNationIdRoute:
    WorldsWorldIdNationsNationIdRouteWithChildren,
  WorldsWorldIdNationsIndexRoute: WorldsWorldIdNationsIndexRoute,
}

const WorldsWorldIdNationsRouteWithChildren =
  WorldsWorldIdNationsRoute._addFileChildren(WorldsWorldIdNationsRouteChildren)

interface WorldsWorldIdRouteChildren {
  WorldsWorldIdConfigurationRoute: typeof WorldsWorldIdConfigurationRoute
  WorldsWorldIdNationsRoute: typeof WorldsWorldIdNationsRouteWithChildren
  WorldsWorldIdIndexRoute: typeof WorldsWorldIdIndexRoute
  WorldsWorldIdCitizensCitizenIdRoute: typeof WorldsWorldIdCitizensCitizenIdRoute
}

const WorldsWorldIdRouteChildren: WorldsWorldIdRouteChildren = {
  WorldsWorldIdConfigurationRoute: WorldsWorldIdConfigurationRoute,
  WorldsWorldIdNationsRoute: WorldsWorldIdNationsRouteWithChildren,
  WorldsWorldIdIndexRoute: WorldsWorldIdIndexRoute,
  WorldsWorldIdCitizensCitizenIdRoute: WorldsWorldIdCitizensCitizenIdRoute,
}

const WorldsWorldIdRouteWithChildren = WorldsWorldIdRoute._addFileChildren(
  WorldsWorldIdRouteChildren,
)

interface WorldsRouteChildren {
  WorldsWorldIdRoute: typeof WorldsWorldIdRouteWithChildren
  WorldsIndexRoute: typeof WorldsIndexRoute
}

const WorldsRouteChildren: WorldsRouteChildren = {
  WorldsWorldIdRoute: WorldsWorldIdRouteWithChildren,
  WorldsIndexRoute: WorldsIndexRoute,
}

const WorldsRouteWithChildren =
  WorldsRoute._addFileChildren(WorldsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  WorldsRoute: WorldsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
