/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldsIndexRouteImport } from './routes/worlds.index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as WorldsWorldIdRouteImport } from './routes/worlds.$worldId'
import { Route as AuthSetPasswordRouteImport } from './routes/auth.set-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as WorldsWorldIdIndexRouteImport } from './routes/worlds.$worldId.index'
import { Route as WorldsWorldIdNationsRouteImport } from './routes/worlds.$worldId.nations'
import { Route as WorldsWorldIdEventsRouteImport } from './routes/worlds.$worldId.events'
import { Route as WorldsWorldIdConfigurationRouteImport } from './routes/worlds.$worldId.configuration'
import { Route as WorldsWorldIdNationsIndexRouteImport } from './routes/worlds.$worldId.nations.index'
import { Route as WorldsWorldIdEventsIndexRouteImport } from './routes/worlds.$worldId.events.index'
import { Route as WorldsWorldIdNationsNationIdRouteImport } from './routes/worlds.$worldId.nations.$nationId'
import { Route as WorldsWorldIdEventsNewRouteImport } from './routes/worlds.$worldId.events.new'
import { Route as WorldsWorldIdEventsEventIdRouteImport } from './routes/worlds.$worldId.events.$eventId'
import { Route as WorldsWorldIdCitizensCitizenIdRouteImport } from './routes/worlds.$worldId.citizens.$citizenId'
import { Route as WorldsWorldIdNationsNationIdIndexRouteImport } from './routes/worlds.$worldId.nations.$nationId.index'
import { Route as WorldsWorldIdNationsNationIdSettlementsSettlementIdRouteImport } from './routes/worlds.$worldId.nations.$nationId.settlements.$settlementId'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsIndexRoute = WorldsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorldsRoute,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const WorldsWorldIdRoute = WorldsWorldIdRouteImport.update({
  id: '/$worldId',
  path: '/$worldId',
  getParentRoute: () => WorldsRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsWorldIdIndexRoute = WorldsWorldIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorldsWorldIdRoute,
} as any)
const WorldsWorldIdNationsRoute = WorldsWorldIdNationsRouteImport.update({
  id: '/nations',
  path: '/nations',
  getParentRoute: () => WorldsWorldIdRoute,
} as any)
const WorldsWorldIdEventsRoute = WorldsWorldIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => WorldsWorldIdRoute,
} as any)
const WorldsWorldIdConfigurationRoute =
  WorldsWorldIdConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => WorldsWorldIdRoute,
  } as any)
const WorldsWorldIdNationsIndexRoute =
  WorldsWorldIdNationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorldsWorldIdNationsRoute,
  } as any)
const WorldsWorldIdEventsIndexRoute =
  WorldsWorldIdEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorldsWorldIdEventsRoute,
  } as any)
const WorldsWorldIdNationsNationIdRoute =
  WorldsWorldIdNationsNationIdRouteImport.update({
    id: '/$nationId',
    path: '/$nationId',
    getParentRoute: () => WorldsWorldIdNationsRoute,
  } as any)
const WorldsWorldIdEventsNewRoute = WorldsWorldIdEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorldsWorldIdEventsRoute,
} as any)
const WorldsWorldIdEventsEventIdRoute =
  WorldsWorldIdEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => WorldsWorldIdEventsRoute,
  } as any)
const WorldsWorldIdCitizensCitizenIdRoute =
  WorldsWorldIdCitizensCitizenIdRouteImport.update({
    id: '/citizens/$citizenId',
    path: '/citizens/$citizenId',
    getParentRoute: () => WorldsWorldIdRoute,
  } as any)
const WorldsWorldIdNationsNationIdIndexRoute =
  WorldsWorldIdNationsNationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorldsWorldIdNationsNationIdRoute,
  } as any)
const WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute =
  WorldsWorldIdNationsNationIdSettlementsSettlementIdRouteImport.update({
    id: '/settlements/$settlementId',
    path: '/settlements/$settlementId',
    getParentRoute: () => WorldsWorldIdNationsNationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/sign-in': typeof SignInRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/worlds': typeof WorldsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/worlds/$worldId': typeof WorldsWorldIdRouteWithChildren
  '/superadmin/': typeof SuperadminIndexRoute
  '/worlds/': typeof WorldsIndexRoute
  '/worlds/$worldId/configuration': typeof WorldsWorldIdConfigurationRoute
  '/worlds/$worldId/events': typeof WorldsWorldIdEventsRouteWithChildren
  '/worlds/$worldId/nations': typeof WorldsWorldIdNationsRouteWithChildren
  '/worlds/$worldId/': typeof WorldsWorldIdIndexRoute
  '/worlds/$worldId/citizens/$citizenId': typeof WorldsWorldIdCitizensCitizenIdRoute
  '/worlds/$worldId/events/$eventId': typeof WorldsWorldIdEventsEventIdRoute
  '/worlds/$worldId/events/new': typeof WorldsWorldIdEventsNewRoute
  '/worlds/$worldId/nations/$nationId': typeof WorldsWorldIdNationsNationIdRouteWithChildren
  '/worlds/$worldId/events/': typeof WorldsWorldIdEventsIndexRoute
  '/worlds/$worldId/nations/': typeof WorldsWorldIdNationsIndexRoute
  '/worlds/$worldId/nations/$nationId/': typeof WorldsWorldIdNationsNationIdIndexRoute
  '/worlds/$worldId/nations/$nationId/settlements/$settlementId': typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/sign-in': typeof SignInRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/worlds': typeof WorldsIndexRoute
  '/worlds/$worldId/configuration': typeof WorldsWorldIdConfigurationRoute
  '/worlds/$worldId': typeof WorldsWorldIdIndexRoute
  '/worlds/$worldId/citizens/$citizenId': typeof WorldsWorldIdCitizensCitizenIdRoute
  '/worlds/$worldId/events/$eventId': typeof WorldsWorldIdEventsEventIdRoute
  '/worlds/$worldId/events/new': typeof WorldsWorldIdEventsNewRoute
  '/worlds/$worldId/events': typeof WorldsWorldIdEventsIndexRoute
  '/worlds/$worldId/nations': typeof WorldsWorldIdNationsIndexRoute
  '/worlds/$worldId/nations/$nationId': typeof WorldsWorldIdNationsNationIdIndexRoute
  '/worlds/$worldId/nations/$nationId/settlements/$settlementId': typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/sign-in': typeof SignInRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/worlds': typeof WorldsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/worlds/$worldId': typeof WorldsWorldIdRouteWithChildren
  '/superadmin/': typeof SuperadminIndexRoute
  '/worlds/': typeof WorldsIndexRoute
  '/worlds/$worldId/configuration': typeof WorldsWorldIdConfigurationRoute
  '/worlds/$worldId/events': typeof WorldsWorldIdEventsRouteWithChildren
  '/worlds/$worldId/nations': typeof WorldsWorldIdNationsRouteWithChildren
  '/worlds/$worldId/': typeof WorldsWorldIdIndexRoute
  '/worlds/$worldId/citizens/$citizenId': typeof WorldsWorldIdCitizensCitizenIdRoute
  '/worlds/$worldId/events/$eventId': typeof WorldsWorldIdEventsEventIdRoute
  '/worlds/$worldId/events/new': typeof WorldsWorldIdEventsNewRoute
  '/worlds/$worldId/nations/$nationId': typeof WorldsWorldIdNationsNationIdRouteWithChildren
  '/worlds/$worldId/events/': typeof WorldsWorldIdEventsIndexRoute
  '/worlds/$worldId/nations/': typeof WorldsWorldIdNationsIndexRoute
  '/worlds/$worldId/nations/$nationId/': typeof WorldsWorldIdNationsNationIdIndexRoute
  '/worlds/$worldId/nations/$nationId/settlements/$settlementId': typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/sign-in'
    | '/superadmin'
    | '/worlds'
    | '/auth/callback'
    | '/auth/set-password'
    | '/worlds/$worldId'
    | '/superadmin/'
    | '/worlds/'
    | '/worlds/$worldId/configuration'
    | '/worlds/$worldId/events'
    | '/worlds/$worldId/nations'
    | '/worlds/$worldId/'
    | '/worlds/$worldId/citizens/$citizenId'
    | '/worlds/$worldId/events/$eventId'
    | '/worlds/$worldId/events/new'
    | '/worlds/$worldId/nations/$nationId'
    | '/worlds/$worldId/events/'
    | '/worlds/$worldId/nations/'
    | '/worlds/$worldId/nations/$nationId/'
    | '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/sign-in'
    | '/auth/callback'
    | '/auth/set-password'
    | '/superadmin'
    | '/worlds'
    | '/worlds/$worldId/configuration'
    | '/worlds/$worldId'
    | '/worlds/$worldId/citizens/$citizenId'
    | '/worlds/$worldId/events/$eventId'
    | '/worlds/$worldId/events/new'
    | '/worlds/$worldId/events'
    | '/worlds/$worldId/nations'
    | '/worlds/$worldId/nations/$nationId'
    | '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
  id:
    | '__root__'
    | '/'
    | '/notifications'
    | '/sign-in'
    | '/superadmin'
    | '/worlds'
    | '/auth/callback'
    | '/auth/set-password'
    | '/worlds/$worldId'
    | '/superadmin/'
    | '/worlds/'
    | '/worlds/$worldId/configuration'
    | '/worlds/$worldId/events'
    | '/worlds/$worldId/nations'
    | '/worlds/$worldId/'
    | '/worlds/$worldId/citizens/$citizenId'
    | '/worlds/$worldId/events/$eventId'
    | '/worlds/$worldId/events/new'
    | '/worlds/$worldId/nations/$nationId'
    | '/worlds/$worldId/events/'
    | '/worlds/$worldId/nations/'
    | '/worlds/$worldId/nations/$nationId/'
    | '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationsRoute: typeof NotificationsRoute
  SignInRoute: typeof SignInRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  WorldsRoute: typeof WorldsRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/': {
      id: '/worlds/'
      path: '/'
      fullPath: '/worlds/'
      preLoaderRoute: typeof WorldsIndexRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/worlds/$worldId': {
      id: '/worlds/$worldId'
      path: '/$worldId'
      fullPath: '/worlds/$worldId'
      preLoaderRoute: typeof WorldsWorldIdRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$worldId/': {
      id: '/worlds/$worldId/'
      path: '/'
      fullPath: '/worlds/$worldId/'
      preLoaderRoute: typeof WorldsWorldIdIndexRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/$worldId/nations': {
      id: '/worlds/$worldId/nations'
      path: '/nations'
      fullPath: '/worlds/$worldId/nations'
      preLoaderRoute: typeof WorldsWorldIdNationsRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/$worldId/events': {
      id: '/worlds/$worldId/events'
      path: '/events'
      fullPath: '/worlds/$worldId/events'
      preLoaderRoute: typeof WorldsWorldIdEventsRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/$worldId/configuration': {
      id: '/worlds/$worldId/configuration'
      path: '/configuration'
      fullPath: '/worlds/$worldId/configuration'
      preLoaderRoute: typeof WorldsWorldIdConfigurationRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/$worldId/nations/': {
      id: '/worlds/$worldId/nations/'
      path: '/'
      fullPath: '/worlds/$worldId/nations/'
      preLoaderRoute: typeof WorldsWorldIdNationsIndexRouteImport
      parentRoute: typeof WorldsWorldIdNationsRoute
    }
    '/worlds/$worldId/events/': {
      id: '/worlds/$worldId/events/'
      path: '/'
      fullPath: '/worlds/$worldId/events/'
      preLoaderRoute: typeof WorldsWorldIdEventsIndexRouteImport
      parentRoute: typeof WorldsWorldIdEventsRoute
    }
    '/worlds/$worldId/nations/$nationId': {
      id: '/worlds/$worldId/nations/$nationId'
      path: '/$nationId'
      fullPath: '/worlds/$worldId/nations/$nationId'
      preLoaderRoute: typeof WorldsWorldIdNationsNationIdRouteImport
      parentRoute: typeof WorldsWorldIdNationsRoute
    }
    '/worlds/$worldId/events/new': {
      id: '/worlds/$worldId/events/new'
      path: '/new'
      fullPath: '/worlds/$worldId/events/new'
      preLoaderRoute: typeof WorldsWorldIdEventsNewRouteImport
      parentRoute: typeof WorldsWorldIdEventsRoute
    }
    '/worlds/$worldId/events/$eventId': {
      id: '/worlds/$worldId/events/$eventId'
      path: '/$eventId'
      fullPath: '/worlds/$worldId/events/$eventId'
      preLoaderRoute: typeof WorldsWorldIdEventsEventIdRouteImport
      parentRoute: typeof WorldsWorldIdEventsRoute
    }
    '/worlds/$worldId/citizens/$citizenId': {
      id: '/worlds/$worldId/citizens/$citizenId'
      path: '/citizens/$citizenId'
      fullPath: '/worlds/$worldId/citizens/$citizenId'
      preLoaderRoute: typeof WorldsWorldIdCitizensCitizenIdRouteImport
      parentRoute: typeof WorldsWorldIdRoute
    }
    '/worlds/$worldId/nations/$nationId/': {
      id: '/worlds/$worldId/nations/$nationId/'
      path: '/'
      fullPath: '/worlds/$worldId/nations/$nationId/'
      preLoaderRoute: typeof WorldsWorldIdNationsNationIdIndexRouteImport
      parentRoute: typeof WorldsWorldIdNationsNationIdRoute
    }
    '/worlds/$worldId/nations/$nationId/settlements/$settlementId': {
      id: '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
      path: '/settlements/$settlementId'
      fullPath: '/worlds/$worldId/nations/$nationId/settlements/$settlementId'
      preLoaderRoute: typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRouteImport
      parentRoute: typeof WorldsWorldIdNationsNationIdRoute
    }
  }
}

interface SuperadminRouteChildren {
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface WorldsWorldIdEventsRouteChildren {
  WorldsWorldIdEventsEventIdRoute: typeof WorldsWorldIdEventsEventIdRoute
  WorldsWorldIdEventsNewRoute: typeof WorldsWorldIdEventsNewRoute
  WorldsWorldIdEventsIndexRoute: typeof WorldsWorldIdEventsIndexRoute
}

const WorldsWorldIdEventsRouteChildren: WorldsWorldIdEventsRouteChildren = {
  WorldsWorldIdEventsEventIdRoute: WorldsWorldIdEventsEventIdRoute,
  WorldsWorldIdEventsNewRoute: WorldsWorldIdEventsNewRoute,
  WorldsWorldIdEventsIndexRoute: WorldsWorldIdEventsIndexRoute,
}

const WorldsWorldIdEventsRouteWithChildren =
  WorldsWorldIdEventsRoute._addFileChildren(WorldsWorldIdEventsRouteChildren)

interface WorldsWorldIdNationsNationIdRouteChildren {
  WorldsWorldIdNationsNationIdIndexRoute: typeof WorldsWorldIdNationsNationIdIndexRoute
  WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute: typeof WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute
}

const WorldsWorldIdNationsNationIdRouteChildren: WorldsWorldIdNationsNationIdRouteChildren =
  {
    WorldsWorldIdNationsNationIdIndexRoute:
      WorldsWorldIdNationsNationIdIndexRoute,
    WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute:
      WorldsWorldIdNationsNationIdSettlementsSettlementIdRoute,
  }

const WorldsWorldIdNationsNationIdRouteWithChildren =
  WorldsWorldIdNationsNationIdRoute._addFileChildren(
    WorldsWorldIdNationsNationIdRouteChildren,
  )

interface WorldsWorldIdNationsRouteChildren {
  WorldsWorldIdNationsNationIdRoute: typeof WorldsWorldIdNationsNationIdRouteWithChildren
  WorldsWorldIdNationsIndexRoute: typeof WorldsWorldIdNationsIndexRoute
}

const WorldsWorldIdNationsRouteChildren: WorldsWorldIdNationsRouteChildren = {
  WorldsWorldIdNationsNationIdRoute:
    WorldsWorldIdNationsNationIdRouteWithChildren,
  WorldsWorldIdNationsIndexRoute: WorldsWorldIdNationsIndexRoute,
}

const WorldsWorldIdNationsRouteWithChildren =
  WorldsWorldIdNationsRoute._addFileChildren(WorldsWorldIdNationsRouteChildren)

interface WorldsWorldIdRouteChildren {
  WorldsWorldIdConfigurationRoute: typeof WorldsWorldIdConfigurationRoute
  WorldsWorldIdEventsRoute: typeof WorldsWorldIdEventsRouteWithChildren
  WorldsWorldIdNationsRoute: typeof WorldsWorldIdNationsRouteWithChildren
  WorldsWorldIdIndexRoute: typeof WorldsWorldIdIndexRoute
  WorldsWorldIdCitizensCitizenIdRoute: typeof WorldsWorldIdCitizensCitizenIdRoute
}

const WorldsWorldIdRouteChildren: WorldsWorldIdRouteChildren = {
  WorldsWorldIdConfigurationRoute: WorldsWorldIdConfigurationRoute,
  WorldsWorldIdEventsRoute: WorldsWorldIdEventsRouteWithChildren,
  WorldsWorldIdNationsRoute: WorldsWorldIdNationsRouteWithChildren,
  WorldsWorldIdIndexRoute: WorldsWorldIdIndexRoute,
  WorldsWorldIdCitizensCitizenIdRoute: WorldsWorldIdCitizensCitizenIdRoute,
}

const WorldsWorldIdRouteWithChildren = WorldsWorldIdRoute._addFileChildren(
  WorldsWorldIdRouteChildren,
)

interface WorldsRouteChildren {
  WorldsWorldIdRoute: typeof WorldsWorldIdRouteWithChildren
  WorldsIndexRoute: typeof WorldsIndexRoute
}

const WorldsRouteChildren: WorldsRouteChildren = {
  WorldsWorldIdRoute: WorldsWorldIdRouteWithChildren,
  WorldsIndexRoute: WorldsIndexRoute,
}

const WorldsRouteWithChildren =
  WorldsRoute._addFileChildren(WorldsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationsRoute: NotificationsRoute,
  SignInRoute: SignInRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  WorldsRoute: WorldsRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
