/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldsIndexRouteImport } from './routes/worlds.index'
import { Route as WorldsWorldSlugRouteImport } from './routes/worlds.$worldSlug'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsIndexRoute = WorldsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorldsRoute,
} as any)
const WorldsWorldSlugRoute = WorldsWorldSlugRouteImport.update({
  id: '/$worldSlug',
  path: '/$worldSlug',
  getParentRoute: () => WorldsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/worlds': typeof WorldsRouteWithChildren
  '/worlds/$worldSlug': typeof WorldsWorldSlugRoute
  '/worlds/': typeof WorldsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/worlds/$worldSlug': typeof WorldsWorldSlugRoute
  '/worlds': typeof WorldsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/worlds': typeof WorldsRouteWithChildren
  '/worlds/$worldSlug': typeof WorldsWorldSlugRoute
  '/worlds/': typeof WorldsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/worlds' | '/worlds/$worldSlug' | '/worlds/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/worlds/$worldSlug' | '/worlds'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/worlds'
    | '/worlds/$worldSlug'
    | '/worlds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  WorldsRoute: typeof WorldsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/': {
      id: '/worlds/'
      path: '/'
      fullPath: '/worlds/'
      preLoaderRoute: typeof WorldsIndexRouteImport
      parentRoute: typeof WorldsRoute
    }
    '/worlds/$worldSlug': {
      id: '/worlds/$worldSlug'
      path: '/$worldSlug'
      fullPath: '/worlds/$worldSlug'
      preLoaderRoute: typeof WorldsWorldSlugRouteImport
      parentRoute: typeof WorldsRoute
    }
  }
}

interface WorldsRouteChildren {
  WorldsWorldSlugRoute: typeof WorldsWorldSlugRoute
  WorldsIndexRoute: typeof WorldsIndexRoute
}

const WorldsRouteChildren: WorldsRouteChildren = {
  WorldsWorldSlugRoute: WorldsWorldSlugRoute,
  WorldsIndexRoute: WorldsIndexRoute,
}

const WorldsRouteWithChildren =
  WorldsRoute._addFileChildren(WorldsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  WorldsRoute: WorldsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
