-- Migration: add_citizen_memories
-- Adds citizen_memories table for persistent per-NPC memory logs, manually
-- curated by admins or auto-generated by events. Establishes RLS (admin-only:
-- super admins and world admins of citizen's world) and three mutation RPCs:
-- add_citizen_memory, update_citizen_memory, delete_citizen_memory.
--
-- Error contract (RPCs):
--   P0002 (no_data_found)          – null params, citizen not found
--   42501 (insufficient_privilege) – caller lacks admin authority
--   P0001 (raise_exception)        – world is archived, cross-world citizen,
--                                    text exceeds limits, turn number out of
--                                    valid range
-- ---------------------------------------------------------------------------
-- citizen_memories
-- ---------------------------------------------------------------------------
create table public.citizen_memories (
  id uuid primary key default gen_random_uuid(),
  world_id uuid not null references public.worlds (id) on delete cascade,
  citizen_id uuid not null references public.citizens (id) on delete cascade,
  memory_text text not null,
  occurred_on_turn_number integer not null,
  source text not null,
  event_id uuid references public.events (id) on delete set null,
  created_by_user_id uuid references public.users (id) on delete set null,
  created_at timestamptz not null default now(),
  constraint citizen_memories_source_check check (source in ('manual', 'event')),
  constraint citizen_memories_memory_text_length_check check (char_length(btrim(memory_text)) >= 1),
  constraint citizen_memories_memory_text_max_length_check check (char_length(memory_text) <= 1000),
  constraint citizen_memories_turn_number_check check (occurred_on_turn_number >= 0)
);

create index citizen_memories_world_id_idx on public.citizen_memories (world_id);

create index citizen_memories_citizen_turn_idx on public.citizen_memories (citizen_id, occurred_on_turn_number);

alter table public.citizen_memories enable row level security;

-- ---------------------------------------------------------------------------
-- RLS Policies: admin-only (super admin + world admin)
-- ---------------------------------------------------------------------------
create policy "citizen_memories_select_super_admin" on public.citizen_memories for
select
  to authenticated using (public.is_super_admin ());

create policy "citizen_memories_select_world_admin" on public.citizen_memories for
select
  to authenticated using (public.is_world_admin (world_id));

create policy "citizen_memories_insert_super_admin" on public.citizen_memories for insert to authenticated
with
  check (public.is_super_admin ());

create policy "citizen_memories_insert_world_admin" on public.citizen_memories for insert to authenticated
with
  check (public.is_world_admin (world_id));

create policy "citizen_memories_update_super_admin" on public.citizen_memories
for update
  to authenticated using (public.is_super_admin ())
with
  check (public.is_super_admin ());

create policy "citizen_memories_update_world_admin" on public.citizen_memories
for update
  to authenticated using (public.is_world_admin (world_id))
with
  check (public.is_world_admin (world_id));

create policy "citizen_memories_delete_super_admin" on public.citizen_memories for delete to authenticated using (public.is_super_admin ());

create policy "citizen_memories_delete_world_admin" on public.citizen_memories for delete to authenticated using (public.is_world_admin (world_id));

-- Revoke default authenticated permissions; grant only what RLS allows
revoke all on public.citizen_memories
from
  authenticated;

grant
select
,
  insert,
update,
delete on public.citizen_memories to authenticated;

-- ---------------------------------------------------------------------------
-- Trigger: Validate that world_id matches the citizen's world_id
-- ---------------------------------------------------------------------------
create or replace function public.validate_citizen_memories_world_id () returns trigger language plpgsql
set
  search_path = '' as $$
declare
  v_citizen_world_id uuid;
begin
  -- Fetch the citizen's actual world_id
  select c.world_id
    into v_citizen_world_id
    from public.citizens c
   where c.id = new.citizen_id;

  -- Ensure citizen exists and world_id matches
  if v_citizen_world_id is null then
    raise exception 'citizen not found' using errcode = 'P0002';
  end if;

  if v_citizen_world_id <> new.world_id then
    raise exception 'citizen does not belong to the specified world'
      using errcode = 'P0001';
  end if;

  return new;
end
$$;

create trigger citizen_memories_validate_world_id before insert
or
update on public.citizen_memories for each row
execute function public.validate_citizen_memories_world_id ();

-- ---------------------------------------------------------------------------
-- RPC: add_citizen_memory
-- Inserts a manual memory for a citizen. Validates:
--   - Caller is super admin or world admin of citizen's world
--   - Citizen exists and belongs to that world
--   - Text trimmed and within length bounds
--   - Turn number is non-negative and within world's current turn + 100 bound
-- ---------------------------------------------------------------------------
create or replace function public.add_citizen_memory (
  p_citizen_id uuid,
  p_memory_text text,
  p_occurred_on_turn_number integer
) returns table (id uuid) language plpgsql security definer
set
  search_path = '' as $$
declare
  v_world_id uuid;
  v_current_turn integer;
  v_trimmed_text text;
begin
  -- Null guard
  if p_citizen_id is null
     or p_memory_text is null
     or p_occurred_on_turn_number is null
  then
    raise exception 'not found' using errcode = 'P0002';
  end if;

  -- Trim and validate text
  v_trimmed_text := btrim(p_memory_text);
  if char_length(v_trimmed_text) < 1 then
    raise exception 'memory text must not be empty' using errcode = 'P0001';
  end if;

  if char_length(v_trimmed_text) > 1000 then
    raise exception 'memory text exceeds maximum length (1000 characters)'
      using errcode = 'P0001';
  end if;

  -- Resolve citizen → world
  select c.world_id
    into v_world_id
    from public.citizens c
   where c.id = p_citizen_id;

  if v_world_id is null then
    raise exception 'not found' using errcode = 'P0002';
  end if;

  -- Archived world guard
  if public.world_is_archived(v_world_id) then
    raise exception 'world is archived' using errcode = 'P0001';
  end if;

  -- Auth: super admin or world admin of citizen's world
  if not (public.is_super_admin() or public.is_world_admin(v_world_id)) then
    raise exception 'insufficient privilege' using errcode = '42501';
  end if;

  -- Turn number validation: >= 0 and <= current_turn + 100
  select w.current_turn_number
    into v_current_turn
    from public.worlds w
   where w.id = v_world_id;

  if p_occurred_on_turn_number < 0 then
    raise exception 'turn number must be >= 0' using errcode = 'P0001';
  end if;

  if p_occurred_on_turn_number > v_current_turn + 100 then
    raise exception
      'turn number must not exceed current turn + 100 future bound'
      using errcode = 'P0001';
  end if;

  -- Insert memory with source='manual'
  insert into public.citizen_memories (
    world_id,
    citizen_id,
    memory_text,
    occurred_on_turn_number,
    source,
    created_by_user_id
  )
  values (
    v_world_id,
    p_citizen_id,
    v_trimmed_text,
    p_occurred_on_turn_number,
    'manual',
    auth.uid()
  )
  returning citizen_memories.id into id;

  return next;
end
$$;

-- ---------------------------------------------------------------------------
-- RPC: update_citizen_memory
-- Updates an existing memory. Validates:
--   - Caller is super admin or world admin of memory's world
--   - Memory exists
--   - New text (if provided) is trimmed and within length bounds
--   - New turn number (if provided) is non-negative and within world's bound
-- ---------------------------------------------------------------------------
create or replace function public.update_citizen_memory (
  p_memory_id uuid,
  p_memory_text text,
  p_occurred_on_turn_number integer
) returns table (id uuid) language plpgsql security definer
set
  search_path = '' as $$
declare
  v_world_id uuid;
  v_current_turn integer;
  v_trimmed_text text;
  v_result_id uuid;
begin
  -- Null guard: at least memory_id must be present
  if p_memory_id is null then
    raise exception 'not found' using errcode = 'P0002';
  end if;

  -- Resolve memory → world
  select cm.world_id
    into v_world_id
    from public.citizen_memories cm
   where cm.id = p_memory_id;

  if v_world_id is null then
    raise exception 'not found' using errcode = 'P0002';
  end if;

  -- Archived world guard
  if public.world_is_archived(v_world_id) then
    raise exception 'world is archived' using errcode = 'P0001';
  end if;

  -- Auth: super admin or world admin of memory's world
  if not (public.is_super_admin() or public.is_world_admin(v_world_id)) then
    raise exception 'insufficient privilege' using errcode = '42501';
  end if;

  -- Validate new text if provided
  if p_memory_text is not null then
    v_trimmed_text := btrim(p_memory_text);
    if char_length(v_trimmed_text) < 1 then
      raise exception 'memory text must not be empty' using errcode = 'P0001';
    end if;

    if char_length(v_trimmed_text) > 1000 then
      raise exception 'memory text exceeds maximum length (1000 characters)'
        using errcode = 'P0001';
    end if;
  end if;

  -- Validate new turn number if provided
  if p_occurred_on_turn_number is not null then
    select w.current_turn_number
      into v_current_turn
      from public.worlds w
     where w.id = v_world_id;

    if p_occurred_on_turn_number < 0 then
      raise exception 'turn number must be >= 0' using errcode = 'P0001';
    end if;

    if p_occurred_on_turn_number > v_current_turn + 100 then
      raise exception
        'turn number must not exceed current turn + 100 future bound'
        using errcode = 'P0001';
    end if;
  end if;

  -- Update memory
  update public.citizen_memories
    set
      memory_text = coalesce(v_trimmed_text, memory_text),
      occurred_on_turn_number = coalesce(
        p_occurred_on_turn_number,
        occurred_on_turn_number
      )
   where citizen_memories.id = p_memory_id
  returning citizen_memories.id into v_result_id;

  id := v_result_id;
  return next;
end
$$;

-- ---------------------------------------------------------------------------
-- RPC: delete_citizen_memory
-- Deletes a memory. Validates:
--   - Caller is super admin or world admin of memory's world
--   - Memory exists
-- ---------------------------------------------------------------------------
create or replace function public.delete_citizen_memory (p_memory_id uuid) returns void language plpgsql security definer
set
  search_path = '' as $$
declare
  v_world_id uuid;
begin
  -- Null guard
  if p_memory_id is null then
    raise exception 'not found' using errcode = 'P0002';
  end if;

  -- Resolve memory → world
  select cm.world_id
    into v_world_id
    from public.citizen_memories cm
   where cm.id = p_memory_id;

  if v_world_id is null then
    raise exception 'not found' using errcode = 'P0002';
  end if;

  -- Archived world guard
  if public.world_is_archived(v_world_id) then
    raise exception 'world is archived' using errcode = 'P0001';
  end if;

  -- Auth: super admin or world admin of memory's world
  if not (public.is_super_admin() or public.is_world_admin(v_world_id)) then
    raise exception 'insufficient privilege' using errcode = '42501';
  end if;

  -- Delete memory
  delete from public.citizen_memories where id = p_memory_id;
end
$$;
